name: Publish Extension
on:
  push:
    branches: main
    paths:
      - "src/**"
      - "package.json"
      - ".github/workflows/main.yaml"

env:
  API_URL: https://lambda.roamjs.com
  ROAMJS_DEVELOPER_TOKEN: ${{ secrets.ROAMJS_DEVELOPER_TOKEN }}
  ROAMJS_EMAIL: support@roamjs.com
  ROAMJS_EXTENSION_ID: workbench
  ROAMJS_RELEASE_TOKEN: ${{ secrets.ROAMJS_RELEASE_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: build
        run: npx roamjs-scripts build
      - name: publish
        run: npx roamjs-scripts publish --depot
      - name: build developer mode
        run: npx roamjs-scripts build --depot
      - name: package
        run: zip -q $ROAMJS_EXTENSION_ID.zip README.md extension.js package.json
      - name: Deploy to RoamJS
        run: aws s3 cp $ROAMJS_EXTENSION_ID.zip s3://roamjs.com/downloads/$ROAMJS_EXTENSION_ID.zip
